repos:
  - repo: https://github.com/hbrach/backendDev/new/feature/backendDev
    rev: v1.0.0
    hooks:
      - id: pre_commit_hook
        stages: [commit]
      - id: post_commit_hook
        stages: [post-commit]
